### ISSUE TITLE
Doesn't seem to allow variation in playback from memory or flash 

### ISSUE THREAD

**Issue by GeertBoer** [newdigate/teensy-variable-playback#1]

**Comment by newdigate** [comment]
Its untested, but I've made a branch with a version with theoretically works with arrays, 
https://github.com/newdigate/teensy-variable-playback/tree/experimental
You might need to modify it to work with flash memory, I haven't tried that yet, either...

adds AudioPlayArrayResmp (using ResamplingArrayReader), defined in src/playarrayresmp.h
