### ISSUE TITLE
While playing different files from sd, application will freeze sporadically

### ISSUE THREAD

**Issue by pqaudio** [newdigate/teensy-variable-playback#4]
Hi,

when playing different files from sd, wav or raw, calling the class/function ResamplingSdReader::play(const char *filename) sometimes leads into an application freezer.
I fixed this by using strncpy instead of strcpy at line 123 in file ResamplingSdReader.cpp.

My suggestion would be than, changing this line from:

strcpy(_filename, filename);

to:

strncpy(_filename, filename, strlen(filename));

Thank you.
Kind regards,

Rotzbengel

**Comment by newdigate** [comment]
Thank you, I've updated with your suggestion. Really appreciate your time and effort! Cheers!
